#!/usr/bin/env python3
"""
mapkit.py — lay out an "atlas" scene on the shared basemap (docs/assets/img/world.svg).

Atlas scenes keep the site's standard 500 × 400 stage viewBox, so labels and strokes
match every other scene. This script works out where a lon/lat window lands in that
box and prints ready-to-paste SVG: the sea, the land (<use> of the shared file), any
named rivers, and pixel positions for every marker and route. Never hand-place a map
marker — run this, paste its output, then add data-step-show / data-step-draw.

    python3 scripts/mapkit.py --bounds W,S,E,N [options]

  --bounds W,S,E,N    lon/lat window to fit (W > E means "crosses the antimeridian")
  --parallel LAT      standard parallel for the equirectangular projection
                      (default: window centre, clamped to ±60; use 0 for world views)
  --pt "Label|lat|lon"         a marker (repeatable)
  --route "Name|lat,lon;lat,lon;…"  a smooth route through waypoints (repeatable)
  --river nile,tigris,…        named rivers to emit as highlighted <use> layers
  --ice                        ice-age coastline: land fill everywhere, sea only where
                               deeper than 200 m, modern coast dashed on top
  --id PREFIX                  id prefix for defs (default "a")
  --size WxH                   stage size (default 500x400)

Output is plain text: a paste-ready <g class="atlas"> block plus a table of marker
pixels. Markers outside the stage are flagged so you can widen the window.
"""
import argparse, math, sys


def parse_args():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--bounds", required=True)
    ap.add_argument("--parallel", type=float)
    ap.add_argument("--pt", action="append", default=[])
    ap.add_argument("--route", action="append", default=[])
    ap.add_argument("--river", default="")
    ap.add_argument("--ice", action="store_true")
    ap.add_argument("--id", default="a")
    ap.add_argument("--size", default="500x400")
    ap.add_argument("--href", default="../assets/img/world.svg")
    return ap.parse_args()


def main():
    a = parse_args()
    W, S, E, N = [float(v) for v in a.bounds.split(",")]
    wrap = E < W
    if wrap:
        E += 360.0
    VW, VH = [float(v) for v in a.size.lower().split("x")]
    lat_c = (S + N) / 2
    lon_c = (W + E) / 2
    par = a.parallel if a.parallel is not None else max(-60.0, min(60.0, lat_c))
    k = math.cos(math.radians(par))
    s = min(VW / ((E - W) * k), VH / (N - S))
    sx, sy = s * k, s

    def lon_norm(lon):
        if wrap and lon < W - 1e-9:
            lon += 360.0
        return lon

    def px(lat, lon):
        lon = lon_norm(lon)
        return VW / 2 + sx * (lon - lon_c), VH / 2 - sy * (lat - lat_c)

    # basemap coords: x0 = lon + 180, y0 = 90 - lat  ->  px = sx*x0 + e, py = sy*y0 + f
    e = VW / 2 - sx * (180.0 + lon_c)
    f = VH / 2 - sy * (90.0 - lat_c)
    mats = [(e, f)]
    if wrap or E > 180:
        mats.append((e + sx * 360.0, f))
    if W < -180:
        mats.append((e - sx * 360.0, f))

    def m(ee, ff):
        return f"matrix({sx:.4f} 0 0 {sy:.4f} {ee:.2f} {ff:.2f})"

    href = a.href
    out = []
    out.append(f'<!-- atlas: bounds {a.bounds} · standard parallel {par:.1f}° · generated by scripts/mapkit.py -->')
    out.append('<g class="atlas">')
    if a.ice:
        out.append(f'  <rect class="atlas__iceland" width="{VW:g}" height="{VH:g}"/>')
        for ee, ff in mats:
            out.append(f'  <use class="atlas__sea" href="{href}#deep" transform="{m(ee, ff)}"/>')
        for ee, ff in mats:
            out.append(f'  <use class="atlas__coast-now" href="{href}#land" transform="{m(ee, ff)}"/>')
    else:
        out.append(f'  <rect class="atlas__sea" width="{VW:g}" height="{VH:g}"/>')
        for ee, ff in mats:
            out.append(f'  <use class="atlas__land" href="{href}#land" transform="{m(ee, ff)}"/>')
    for ee, ff in mats:
        out.append(f'  <use class="atlas__lakes" href="{href}#lakes" transform="{m(ee, ff)}"/>')
        out.append(f'  <use class="atlas__rivers" href="{href}#rivers" transform="{m(ee, ff)}"/>')
    for r in [r.strip() for r in a.river.split(",") if r.strip()]:
        slug = r[2:] if r.startswith("r-") else r
        for ee, ff in mats:
            out.append(f'  <use class="atlas__river" href="{href}#r-{slug}" transform="{m(ee, ff)}"/>  <!-- add data-step-show="N" -->')
    out.append('</g>')

    table = []
    for spec in a.pt:
        try:
            label, lat, lon = spec.split("|")
            x, y = px(float(lat), float(lon))
        except ValueError:
            sys.exit(f"bad --pt {spec!r}; use 'Label|lat|lon'")
        inside = 0 <= x <= VW and 0 <= y <= VH
        table.append((label, float(lat), float(lon), x, y, inside))

    routes = []
    for spec in a.route:
        try:
            name, pts = spec.split("|")
            ll = [tuple(float(v) for v in p.split(",")) for p in pts.split(";") if p.strip()]
        except ValueError:
            sys.exit(f"bad --route {spec!r}; use 'Name|lat,lon;lat,lon;…'")
        P = [px(lat, lon) for lat, lon in ll]
        if len(P) < 2:
            continue
        # Catmull-Rom -> cubic Bézier for a smooth, drawable route
        d = f"M{P[0][0]:.1f} {P[0][1]:.1f}"
        for i in range(len(P) - 1):
            p0 = P[i - 1] if i > 0 else P[i]
            p1, p2 = P[i], P[i + 1]
            p3 = P[i + 2] if i + 2 < len(P) else P[i + 1]
            c1 = (p1[0] + (p2[0] - p0[0]) / 6, p1[1] + (p2[1] - p0[1]) / 6)
            c2 = (p2[0] - (p3[0] - p1[0]) / 6, p2[1] - (p3[1] - p1[1]) / 6)
            d += f" C{c1[0]:.1f} {c1[1]:.1f} {c2[0]:.1f} {c2[1]:.1f} {p2[0]:.1f} {p2[1]:.1f}"
        routes.append((name, d))

    print("\n".join(out))
    if table:
        print("\n<!-- markers (x, y in stage px) -->")
        for label, lat, lon, x, y, inside in table:
            flag = "" if inside else "   <-- OUTSIDE THE STAGE: widen --bounds"
            print(f'<circle class="atlas__pin" cx="{x:.1f}" cy="{y:.1f}" r="4"/>  <!-- {label} ({lat:.2f}, {lon:.2f}) -->{flag}')
    if routes:
        print("\n<!-- routes: add class=\"draw\" pathLength=\"1\" data-step-draw=\"N\" -->")
        for name, d in routes:
            print(f'<path class="atlas__route draw" pathLength="1" d="{d}"/>  <!-- {name} -->')


if __name__ == "__main__":
    main()
